"""
Django settings for order_project project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-re2xthlu*u+r&w=ds1^-i7_*9f7@2qd723&e^&i^hrg$f9dmt5"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'simpleui',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # 'bootstrap4',
    'donglong_order.apps.DonglongOrderConfig',

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "order_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, 'templates')]
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "order_project.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default':
        {
            'ENGINE': 'django.db.backends.mysql',  # 数据库引擎
            'NAME': 'donglong_ordering',  # 数据库名称
            'PORT': 3306,  # 端口
            'USER': 'root',  # 数据库用户名
            'HOST': '10.18.22.137',  # 数据库地址，本机 ip 地址 127.0.0.1
            'PASSWORD': 'QWer1234%',  # 数据库密码
        }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator", },
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator", },
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator", },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# 更改默认语言为中文
LANGUAGE_CODE = 'zh-hans'

# 更改时区为上海
TIME_ZONE = 'Asia/Shanghai'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# simpleUI相关的广告内容
SIMPLEUI_LOGO = 'https://fileihr.zhaopin.com/036/704/036704391/logo/4f37adbe-b103-4823-ac3a-f3d9ac4d4ef6.png'
# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_ACTION = False
# 修改首页设置, 指向新创建的控制面板
SIMPLEUI_HOME_PAGE = '/dl_order/order/getData'
# SIMPLEUI_HOME_TITLE = '数据面板'
# SIMPLEUI_HOME_ICON = 'fa fa-eye'

SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep': False,
    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
    'menu_display': ['订单管理', '菜品管理', '包间管理', '餐厅管理', '用户管理'],
    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。# 一般建议关闭。
    'dynamic': False,
    'menus': [

        {
            'name': '订单管理',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '堂食订单',
                    'url': '/dl_order/order/getOrderList',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '包间预定',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/dl_order/order/getOrderList',
                    'icon': 'fa fa-tasks',
                },
            ]
        },

        {
            'name': '菜品管理',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '菜品列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/dl_order/order/getDishList',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '新增菜品',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/tasks/task/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '菜品分类',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/tasks/task/',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '每周菜品',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/tasks/task/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },

        {
            'name': '包间管理',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '包间列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/dl_order/order/getData',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '新增包间',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/tasks/task/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
        {
            'app': 'auth',
            'name': '用户管理',
            'icon': 'fas fa-user-shield',
            'models': [
                {
                    'name': '用户列表',
                    'icon': 'fa fa-user',
                    'url': 'auth/user/'
                },
                {
                    'name': '用户组',
                    'icon': 'fa fa-th-list',
                    'url': 'auth/group/'
                }
            ]
        },

        {
            'name': '餐厅管理',
            'icon': 'fa fa-th-list',
            'models': [
                {
                    'name': '餐厅列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/dl_order/order/getDishList',
                    'icon': 'fa fa-tasks'
                },
                {
                    'name': '新增包间',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': '/admin/tasks/task/',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
    ],

}
