# Generated by Django 4.2.11 on 2024-03-13 07:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dishOrder", models.IntegerField(verbose_name="菜品顺序号")),
                ("dishName", models.CharField(max_length=100, verbose_name="菜品名称")),
                ("imageUrl", models.URLField(verbose_name="菜品图片URL")),
                ("stockQuantity", models.IntegerField(verbose_name="库存数量")),
                ("dishStatus", models.BooleanField(default=True, verbose_name="菜品状态")),
                (
                    "dineInDisplayStatus",
                    models.BooleanField(default=True, verbose_name="堂食显示状态"),
                ),
                (
                    "takeoutDisplayStatus",
                    models.BooleanField(default=True, verbose_name="外卖显示状态"),
                ),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
            ],
            options={
                "verbose_name": "菜品",
                "verbose_name_plural": "菜品",
                "db_table": "dish",
            },
        ),
        migrations.CreateModel(
            name="FirstCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoryName",
                    models.CharField(max_length=20, verbose_name="一级分类名称"),
                ),
            ],
            options={
                "verbose_name": "菜品一级分类",
                "verbose_name_plural": "菜品一级分类",
                "db_table": "first_category",
            },
        ),
        migrations.CreateModel(
            name="Manager",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("managerName", models.CharField(max_length=50, verbose_name="管理人员姓名")),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "userName",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "userPassword",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "createdBy",
                    models.ForeignKey(
                        blank=True,
                        db_column="createdBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="donglong_order.manager",
                        verbose_name="创建此管理人员的管理人ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理人员",
                "verbose_name_plural": "管理人员",
                "db_table": "manager",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("orderNumber", models.CharField(max_length=50, verbose_name="订单编号")),
                ("scheduledDate", models.DateField(verbose_name="订单约定日期")),
                ("scheduledTime", models.TimeField(verbose_name="订单约定时间")),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("bz", models.CharField(max_length=50, null=True, verbose_name="备注")),
                ("numberDiners", models.IntegerField(null=True, verbose_name="就餐人数")),
            ],
            options={
                "verbose_name": "订单",
                "verbose_name_plural": "订单",
                "db_table": "order",
            },
        ),
        migrations.CreateModel(
            name="OrderStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statusName", models.CharField(max_length=20, verbose_name="状态名称")),
            ],
            options={
                "verbose_name": "订餐状态",
                "verbose_name_plural": "订餐状态",
                "db_table": "order_status",
            },
        ),
        migrations.CreateModel(
            name="SecondCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoryName",
                    models.CharField(max_length=20, verbose_name="二级分类名称"),
                ),
            ],
            options={
                "verbose_name": "菜品二级分类",
                "verbose_name_plural": "菜品二级分类",
                "db_table": "second_category",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userName", models.CharField(max_length=50, verbose_name="用户名")),
                ("phoneNumber", models.CharField(max_length=15, verbose_name="手机号")),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="UserDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dishId",
                    models.ForeignKey(
                        db_column="dishId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donglong_order.dish",
                        verbose_name="菜品ID",
                    ),
                ),
                (
                    "userId",
                    models.ForeignKey(
                        db_column="userId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donglong_order.user",
                        verbose_name="用户ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户-菜品",
                "verbose_name_plural": "用户-菜品",
                "db_table": "user_dish",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("roomName", models.CharField(max_length=100, verbose_name="包间名称")),
                (
                    "roomConfiguration",
                    models.CharField(max_length=100, verbose_name="包间配置"),
                ),
                ("roomLocation", models.CharField(max_length=100, verbose_name="包间位置")),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                (
                    "createdBy",
                    models.ForeignKey(
                        db_column="createdBy",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_createdby",
                        to="donglong_order.manager",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "lastUpdatedBy",
                    models.ForeignKey(
                        db_column="lastUpdatedBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_lastUpdatedBy",
                        to="donglong_order.manager",
                        verbose_name="最后修改人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "包间",
                "verbose_name_plural": "包间",
                "db_table": "room",
            },
        ),
        migrations.CreateModel(
            name="RestaurantCarousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("carouselName", models.CharField(max_length=100, verbose_name="轮播名称")),
                (
                    "carouselImageUrl",
                    models.CharField(max_length=100, verbose_name="轮播图URL"),
                ),
                (
                    "carouselTimeRange",
                    models.CharField(max_length=100, verbose_name="轮播时间范围"),
                ),
                (
                    "publishedAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="发布时间"),
                ),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                ("carouselType", models.IntegerField(verbose_name="轮播类型")),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                (
                    "createdBy",
                    models.ForeignKey(
                        db_column="createdBy",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_createdby",
                        to="donglong_order.manager",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "lastUpdatedBy",
                    models.ForeignKey(
                        db_column="lastUpdatedBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carousel_lastUpdatedBy",
                        to="donglong_order.manager",
                        verbose_name="最后修改人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "轮播表",
                "verbose_name_plural": "轮播表",
                "db_table": "restaurant_carousel",
            },
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurantName",
                    models.CharField(max_length=100, verbose_name="餐厅名称"),
                ),
                (
                    "restaurantType",
                    models.CharField(max_length=50, verbose_name="餐厅类型"),
                ),
                ("openingHours", models.TextField(verbose_name="营业时间")),
                (
                    "restaurantPhone",
                    models.CharField(max_length=20, verbose_name="餐厅电话"),
                ),
                (
                    "restaurantAddress",
                    models.CharField(max_length=200, verbose_name="餐厅地址"),
                ),
                (
                    "navigationCoordinates",
                    models.CharField(max_length=50, verbose_name="导航坐标"),
                ),
                (
                    "createdAt",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("updatedAt", models.DateTimeField(auto_now=True, verbose_name="修改时间")),
                (
                    "createdBy",
                    models.ForeignKey(
                        db_column="createdBy",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rest_createdby",
                        to="donglong_order.manager",
                        verbose_name="创建人",
                    ),
                ),
                (
                    "lastUpdatedBy",
                    models.ForeignKey(
                        db_column="lastUpdatedBy",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rest_lastUpdatedBy",
                        to="donglong_order.manager",
                        verbose_name="最后修改人员",
                    ),
                ),
            ],
            options={
                "verbose_name": "餐厅表",
                "verbose_name_plural": "餐厅表",
                "db_table": "restaurant",
            },
        ),
        migrations.CreateModel(
            name="OrderDish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dishNum", models.IntegerField(verbose_name="下单菜品数量")),
                (
                    "dishId",
                    models.ForeignKey(
                        db_column="dishId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donglong_order.dish",
                        verbose_name="菜品ID",
                    ),
                ),
                (
                    "orderId",
                    models.ForeignKey(
                        db_column="orderId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donglong_order.order",
                        verbose_name="订单ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单-菜品",
                "verbose_name_plural": "订单-菜品",
                "db_table": "order_dish",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="orderStatus",
            field=models.ForeignKey(
                db_column="orderStatus",
                on_delete=django.db.models.deletion.CASCADE,
                to="donglong_order.orderstatus",
                verbose_name="订餐状态",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="roomId",
            field=models.ForeignKey(
                db_column="roomId",
                on_delete=django.db.models.deletion.CASCADE,
                to="donglong_order.room",
                verbose_name="包间ID",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="userId",
            field=models.ForeignKey(
                db_column="userId",
                on_delete=django.db.models.deletion.CASCADE,
                to="donglong_order.user",
                verbose_name="用户ID",
            ),
        ),
        migrations.CreateModel(
            name="DishTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag1", models.CharField(max_length=50, verbose_name="标签")),
                (
                    "dishId",
                    models.ForeignKey(
                        db_column="dishId",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donglong_order.dish",
                        verbose_name="菜品ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "菜品-标签",
                "verbose_name_plural": "菜品-标签",
                "db_table": "dish_tag",
            },
        ),
        migrations.AddField(
            model_name="dish",
            name="createdBy",
            field=models.ForeignKey(
                db_column="createdBy",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dish_createdby",
                to="donglong_order.manager",
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="firstCategoryId",
            field=models.ForeignKey(
                db_column="firstCategoryId",
                on_delete=django.db.models.deletion.CASCADE,
                to="donglong_order.firstcategory",
                verbose_name="菜品一级分类ID",
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="lastUpdatedBy",
            field=models.ForeignKey(
                db_column="lastUpdatedBy",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dish_lastUpdatedBy",
                to="donglong_order.manager",
                verbose_name="最后修改人员",
            ),
        ),
        migrations.AddField(
            model_name="dish",
            name="secondCategoryId",
            field=models.ForeignKey(
                db_column="secondCategoryId",
                on_delete=django.db.models.deletion.CASCADE,
                to="donglong_order.secondcategory",
                verbose_name="菜品二级分类ID",
            ),
        ),
        migrations.CreateModel(
            name="AuthtokenTokenAdmin",
            fields=[
                (
                    "key",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires", models.DateTimeField()),
                (
                    "manager",
                    models.OneToOneField(
                        db_column="manager",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="donglong_order.manager",
                    ),
                ),
            ],
            options={
                "verbose_name": "权限管理表",
                "verbose_name_plural": "权限管理表",
                "db_table": "authtoken_token_admin",
            },
        ),
    ]
