# Generated by Django 4.2.11 on 2024-03-14 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("donglong_order", "0002_alter_dish_updatedat"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="scheduledTime",),
        migrations.AddField(
            model_name="order",
            name="scheduledTimeEnd",
            field=models.TimeField(default=1, verbose_name="订单约定时间结束"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="scheduledTimeStart",
            field=models.TimeField(default=1, verbose_name="订单约定时间开始"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="roomId",
            field=models.ForeignKey(
                db_column="roomId",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="donglong_order.room",
                verbose_name="包间ID",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="updatedAt",
            field=models.DateTimeField(auto_now=True, null=True, verbose_name="修改时间"),
        ),
    ]
