# Generated by Django 4.2.11 on 2024-03-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donglong_order",
            "0003_remove_order_scheduledtime_order_scheduledtimeend_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="createdAt",
            field=models.DateTimeField(verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="room",
            name="createdAt",
            field=models.DateTimeField(verbose_name="创建时间"),
        ),
        migrations.AlterField(
            model_name="room",
            name="updatedAt",
            field=models.DateTimeField(null=True, verbose_name="修改时间"),
        ),
    ]
